name: builder-smoke

on:
  workflow_dispatch:   # lets you run manually from phone/PC
  push:
    branches: [develop]

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Hit /health
        run: |
          BASE="https://ai-factory-experimental.onrender.com"
          echo "Checking $BASE/health ..."
          curl -fsS "$BASE/health"

      - name: Scaffold test app
        run: |
          BASE="https://ai-factory-experimental.onrender.com"
          echo "Scaffolding via Builder..."
          curl -fsS
