name: Promote Experimental to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Optional release tag (e.g. v0.5.2)"
        required: false

jobs:
  promote:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # needed to push merge/tag
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure remotes and branches
        run: |
          git remote -v
          git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Merge develop -> main (fast-forward if possible)
        run: |
          set -e
          git checkout main
          git merge --ff-only origin/develop || (
            echo "Fast-forward not possible; doing a no-ff merge."
            git merge --no-ff -m "Promote experimental to production" origin/develop
          )
          git push origin main

      - name: Optional tag
        if: ${{ inputs.version != '' }}
        run: |
          git tag ${{ inputs.version }}
          git push origin ${{ inputs.version }}

      - name: Trigger Render production deploy (Deploy Hook)
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"
