name: promote-to-production
on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Merge develop -> main (no fast-forward)
        run: |
          git config user.name "CI"
          git config user.email "ci@example.com"
          git checkout main
          git merge --no-ff origin/develop -m "Promote experimental to production"
          git push origin main
      - name: Wait for PROD to be healthy
        run: |
          BASE="https://ai-factory-production.onrender.com"
          for i in {1..40}; do
            if curl -fsS "$BASE/health" | jq -e '.status=="ok"' >/dev/null; then
              echo "PROD healthy"; exit 0
            fi
            sleep 6
          done
          echo "PROD not healthy in time"; exit 1
      - name: Smoke /bots and /store on PROD
        run: |
          BASE="https://ai-factory-production.onrender.com"
          curl -fsS "$BASE/bots" || true
          code=$(curl -s -o /dev/null -w "%{http_code}" "$BASE/store")
          test "$code" = "200"
  rollback_on_fail:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Revert last main commit
        run: |
          git config user.name "CI"
          git config user.email "ci@example.com"
          git checkout main
          git reset --hard HEAD~1
          git push --force origin main
